site_name: Safer Streets EDA
site_author: Andrew P Smith
site_description: Progress reporting for Safer Streets
repo_url: https://github.com/safer-streets/safer-streets-eda
repo_name: GitHub

theme:
  name: material
  logo: img/safer-streets-small.png
  favicon: img/safer-streets-small.png
  palette:
    #scheme: slate
    primary: teal
    accent: orange
  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - toc:
      permalink: "¶"
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - attr_list
  - md_in_html

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  # - macros:
  #     module_name: docs/macros
      # include_dir: examples
  - blog # articles in draft will not get built/gh-deployed (but are served)


extra:
  consent:
    title: Cookie consent
    description: >-
      This site uses cookies with your permission.
    actions:
      - accept
      - manage
      - reject


